apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: image.lin2ur.cn-rule
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Release.Name }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-image-lin2ur-cn-v1-rule
        port: 9443
    failurePolicy: Fail
    name: mrule.kb.io
    rules:
      - apiGroups:
          - image.lin2ur.cn
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rules
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: image.lin2ur.cn-rule
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Release.Name }}
        namespace: {{ .Release.Namespace }}
        path: /validate-image-lin2ur-cn-v1-rule
        port: 9443
    failurePolicy: Fail
    name: vrule.kb.io
    rules:
      - apiGroups:
          - image.lin2ur.cn
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rules
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Release.Name }}
        namespace: {{ .Release.Namespace }}
        path: /validate-image-lin2ur-cn-v1-mirror
        port: 9443
    failurePolicy: Fail
    name: vmirror.kb.io
    rules:
      - apiGroups:
          - image.lin2ur.cn
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - mirrors
    sideEffects: None