controller:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/lin2ur/k8s-image-operator
    tag: 1.0.0
  imagePullPolicy: IfNotPresent
  nodeSelector: { }
  affinity: { }
  resources: { }
  replicas: 1

mirror:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/lin2ur/k8s-image-operator
    tag: crane-0.19.1
  cleanFinishedMirror: 30m

admissionWebhooks:
  enabled: true
  patch:
    image:
      repository: registry.cn-shenzhen.aliyuncs.com/lin2ur/ingress-nginx-kube-webhook-certgen
      tag: v20221220-controller-v1.5.1-58-g787ea74b6
    enabled: true