apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Release.Name }}-webhook-tls
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tls/tls.crt
              name: tls
              subPath: cert
            - mountPath: /tls/tls.key
              name: tls
              subPath: key
            - mountPath: /tls/ca.crt
              name: tls
              subPath: ca
          env:
            - name: WEBHOOK_CA_CERT_FILE
              value: /tls/ca.crt
            - name: WEBHOOK_SERVICE_NAME
              value: {{ .Release.Name }}
            - name: WEBHOOK_SERVICE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: WEBHOOK_CERT_DIR
              value: /tls
            - name: CRANE_IMAGE
              value: {{ .Values.mirror.craneImage }}
          ports:
            - containerPort: 9443
              name: https
            - containerPort: 8081
              name: healthz
          args:
            - --clean-finished-mirror={{ .Values.mirror.cleanFinishedMirror }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 9443
      targetPort: https
  type: ClusterIP