apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager-role
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - image-operator
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - delete
      - get
      - patch
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - rules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - rules/finalizers
    verbs:
      - update
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - rules/status
    verbs:
      - get
      - patch
      - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-manager-role