apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-controller
rules:
  - verbs:
      - '*'
    apiGroups:
      - image.lin2ur.cn
    resources:
      - rules
  - verbs:
      - '*'
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-manager-role
  {{- if false }}
  name: {{ .Release.Name }}-controller
  {{- end }}