apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager-role
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - mirrors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - mirrors/finalizers
    verbs:
      - update
      - watch
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - mirrors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - rules
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - rules/finalizers
    verbs:
      - update
  - apiGroups:
      - image.lin2ur.cn
    resources:
      - rules/status
    verbs:
      - get
      - patch
      - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-manager-role