image:
  repository: registry.cn-shenzhen.aliyuncs.com/lin2ur/k8s-image-operator
  tag: dev

replicas: 2

admissionWebhooks:
  enabled: true
  patch:
    image:
      repository: rancher/mirrored-ingress-nginx-kube-webhook-certgen
      tag: v20221220-controller-v1.5.1-58-g787ea74b6
    enabled: true