name: Build

on:
  push:
    tags:
      - 'crane-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "CRANE_VERSION=${GITHUB_REF#refs/tags/crane-}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:crane-${{ env.CRANE_VERSION }}'
          build-args: CRANE_VERSION=${{ env.CRANE_VERSION }}
